# This workflow will install build and push the container of the DASH app of this repository.

name: CI/CD Pipeline

on:
  workflow_dispatch: #trigger button
  push:
    branches:
      - main

jobs:
  build-and-push:
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
    - name: Checkout repository #get the source code
      uses: actions/checkout@v2

    # - name: Set up Docker Buildx #install docker
    #   uses: docker/setup-buildx-action@v1
        
    - uses: actions/checkout@v1
    - name: Build & Push Image to DockerHub
      run: |
        sudo echo "${{ secrets.CICD_DASH_TOKEN_DOCKERHUB }}" | docker login -u "reisikei" --password-stdin
        sudo docker image build -t reisikei/pytripplanner:2 .
        sudo docker push reisikei/pytripplanner:2